version: '3.8'

services:
  server:
    build: .
    ports:
      - '5353:5353'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5353/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
